restaking: depositing during bounding period
ComposableFi/emulated-light-client pull request #188
Opened 2024-01-17 06:35 UTC by dhruvja

During bounding period ( period before the bridge is launched ), users can stake their assets without choosing the validator since the validators dont exist yet. The staked tokens get locked in the vault and then when the bridge is launched, the users can set the stake on validator through the following options
- Choose a validator randomly
- Choose a validator from the list of top 10 validators chosen by us
- Choose a particular validator.

Also added `update_bounding_period` which would update the bounding period. 

The update methods are made seperate to isolate them such that one update doesnt fuck up the others.

2024-01-19 17:49 UTC, blasrodri requested changes

2024-01-19 17:49 UTC, blasrodri commented on solana/restaking/programs/restaking/src/lib.rs
> +        if staking_params.total_deposited_amount > staking_params.staking_cap {
>=

2024-01-19 17:50 UTC, dhruvja commented on solana/restaking/programs/restaking/src/lib.rs
> +        if staking_params.total_deposited_amount > staking_params.staking_cap {
it should be fine if its equal right?

2024-01-23 17:07 UTC, blasrodri approved these changes

2024-01-24 12:37 UTC, merged